apiVersion: v2
name: app
description: Helm chart for your amazing app
type: application
version: 0.1.0
dependencies:
    - name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 11.10.3
      condition: minio.enabled
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.1.5
      condition: mongodb.enabled
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.2.0
      condition: redis.enabled

