apiVersion: v2
name: app
description: Helm chart for your amazing app
type: application
version: 0.1.0
dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 11.0.2
      condition: mongodb.enabled
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.3.0
      condition: redis.enabled
    - name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.2
      condition: minio.enabled
