apiVersion: v2
name: app
description: Helm chart for your amazing app
type: application
version: 0.1.0
dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.19
      condition: mongodb.enabled
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 16.13.2
      condition: redis.enabled
    - name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 11.7.4
      condition: minio.enabled
