# Application settings
app:
    # docker image (including tag)
    image: ''

    # image pull secrets
    imagePullSecrets: []

    # image pull policy
    imagePullPolicy: IfNotPresent

    # pods specs
    pods:
        ## Annotations for server pods
        ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
        ##
        serverAnnotations: {}

        ## Annotations for worker pods
        ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
        ##
        workerAnnotations: {}

    ingress:
        annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"

        hosts:
            - host: app.local
              paths: []

        tls: []
        #  - secretName: chart-example-tls
        #    hosts:
        #      - chart-example.local

    # global configuration
    global:
        publicPath: ''
        gzip: ''
        secureCookie: ''

    # redis settings
    redis:
        uri: ''

    # database settings
    database:
        uri: ''
        name: ''
        pool: ''

    # session settings
    session:
        secret: ''
        lifetime: ''

    # smtp settings
    smtp:
        host: ''
        port: ''
        user: ''
        password: ''
        secure: ''
        from: ''

    # storage settings
    storage:
        endpoint: ''
        accessKey: ''
        secretKey: ''
        ssl: ''
        port: ''
        region: ''
        bucket: ''

    # sentry settings
    sentry:
        dsn: ''
        release: ''
        environment: ''
        tracing: ''
        tracesSampleRate: ''

    # limiter settings
    limiter:
        api: ''

    # prometheus settings
    prometheus:
        enabled: ''
        internal: ''
        internalPort: ''
        external: ''
        externalPath: ''
        prefix: ''

    # HorizontalPodAutoscaler config for servers (api)
    serverPodScaler:
        enabled: false
        minReplicas: 1
        maxReplicas: 1
        metrics: {}

    # HorizontalPodAutoscaler for workers
    workerPodScaler:
        enabled: false
        minReplicas: 1
        maxReplicas: 1
        metrics: {}

# html2pdf settings
html2pdf:
    # docker image (including tag)
    image: 'appvantage/html2pdf-service:1.2.1'

    # image pull policy
    imagePullPolicy: IfNotPresent

    # pod scaler
    podScaler:
        enabled: false
        minReplicas: 1
        maxReplicas: 1
        metrics: {}

# Redis settings
redis:
    # should the redis chart be deployed
    enabled: true

    # no password
    usePassword: false

    # architecture type
    architecture: standalone

    auth:
        # no password/authentication
        enabled: false

# MongoDB settings
# when using this sub chart
# please provide information matching your application settings
mongodb:
    enabled: false

    # image to use
    image:
        tag: 5.0.3-debian-10-r19

    # architecture type
    architecture: standalone

# Minion settings
minio:
    enabled: false

    # server mode
    mode: standalone

    # bucket to automatically create
    defaultBuckets: 'app'

## Affinity for pod assignment.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
