version: 2.1

executors:
    node-standalone:
        docker:
            - image: circleci/node:16.4.2
    node-with-dependencies:
        docker:
            - image: circleci/node:16.4.2
              environment:
                  APP_DB_URI: mongodb://root:password@127.0.0.1:27017
                  APP_SESSION_SECRET: localSecret
                  APP_SMTP_PORT: 1025
                  APP_STORAGE_ENDPOINT: localhost
                  APP_STORAGE_PORT: 9000
                  APP_STORAGE_SSL: false
                  APP_STORAGE_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE'
                  APP_STORAGE_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
                  APP_HTML2PDF_ENDPOINT: 'http://html2pdf:3000/'
            - image: circleci/mongo:5.0.0
              environment:
                  MONGO_INITDB_ROOT_USERNAME: root
                  MONGO_INITDB_ROOT_PASSWORD: password
            - image: minio/minio:RELEASE.2021-07-08T01-15-01Z
              command: server /data
              environment:
                  MINIO_ROOT_USER: 'AKIAIOSFODNN7EXAMPLE'
                  MINIO_ROOT_PASSWORD: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
            - image: circleci/redis:6.2.4-alpine
              command: redis-server --appendonly yes
            - image: appvantage/html2pdf-service:1.0.0
              name: html2pdf

jobs:
    deps-install:
        executor: node-standalone
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - yarn-cache-node16-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
                      - yarn-cache-node16-{{ checksum "package.json" }}
                      - yarn-cache-node16
            - run:
                  name: Install depdencies
                  command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
            - save_cache:
                  key: yarn-cache-node16-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - node_modules

    validate-project:
        executor: node-with-dependencies
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Lint source code
                  command: yarn lint --format junit -o ./junit/js-lint-results.xml
            - run:
                  name: Type checking
                  command: yarn tsc
            - run:
                  name: Type checking on cypress
                  command: yarn tsc
                  working_directory: ~/project/cypress
            - run:
                  name: Wait for db
                  command: dockerize -wait tcp://127.0.0.1:27017 -timeout 1m
            - run:
                  name: Unit testing
                  command: yarn test:coverage --reporters=default --reporters=jest-junit
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: ./junit/
            - run:
                  name: Build
                  command: yarn build
                  environment:
                      NODE_ENV: production
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - build
            - store_artifacts:
                  path: ~/project/build
                  destination: build
            - store_artifacts:
                  path: ~/project/report.html
                  destination: report.html
            - run:
                  name: Install Cypress
                  command: |
                      sudo apt-get update
                      sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
                      yarn cypress install
            - run:
                  name: Start server
                  command: node server.js serve
                  background: true
                  working_directory: ~/project/build
            - run:
                  name: Start worker
                  command: node server.js worker
                  background: true
                  working_directory: ~/project/build
            - run:
                  name: Wait for test server
                  command: dockerize -wait http://127.0.0.1:3000 -timeout 5m
            - run:
                  name: Functional testing
                  command: yarn cypress:run
                  environment:
                      CYPRESS_BASE_URL: 'http://localhost:3000'
            - store_artifacts:
                  path: ~/project/cypress/screenshots
                  destination: cypress/screenshots
            - store_artifacts:
                  path: ~/project/cypress/videos
                  destination: cypress/videos
            - run:
                  name: Stop test server & worker
                  command: pkill -SIGQUIT node
            - run:
                  name: Lint commit messages
                  command: node ./devtools/commands/lint-commits.js
            - store_test_results:
                  path: ~/project/junit/
            - store_artifacts:
                  path: ~/project/coverage/
                  destination: coverage

    release:
        executor: node-standalone
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run:
                  name: semantic-release
                  command: yarn semantic-release

workflows:
    version: 2

    main:
        jobs:
            - deps-install
            - validate-project:
                  requires:
                      - deps-install
            - release:
                  filters:
                      branches:
                          only:
                              - /([0-9])+?.([0-9])+?.x/
                              - next
                              - latest
                  requires:
                      - validate-project
