apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-app-configmap"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  # global settings
  {{- with .Values.app.global }}
  {{- include "app.configValue" ( dict "Key" "APP_PUBLIC_PATH" "Value" .publicPath ) }}
  {{- include "app.configValue" ( dict "Key" "APP_GZIP" "Value" .gzip ) }}
  {{- include "app.configValue" ( dict "Key" "APP_SECURE_COOKIE" "Value" .secureCookie ) }}
  {{- include "app.configValue" ( dict "Key" "APP_COOKIE_POLICY" "Value" .cookiePolicy ) }}
  {{- end }}

  # redis settings
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.sentinel.enabled }}
  APP_REDIS_SENTINEL: "true"
  {{- end }}
  {{- else }}
  {{- with .Values.app.redis }}
  {{- include "app.configValue" ( dict "Key" "APP_REDIS_SENTINEL" "Value" .sentinel ) }}
  {{- end }}
  {{- end  }}

  # session settings
  {{- with .Values.app.session }}
  {{- include "app.configValue" ( dict "Key" "APP_SESSION_LIFETIME" "Value" .lifetime ) }}
  {{- end }}

  # smtp settings
  {{- with .Values.app.smtp }}
  {{- include "app.configValue" ( dict "Key" "APP_SMTP_FROM" "Value" .from ) }}
  {{- end }}

  # sentry settings
  {{- with .Values.app.sentry }}
  {{- include "app.configValue" ( dict "Key" "APP_SENTRY_DSN" "Value" .dsn ) }}
  {{- include "app.configValue" ( dict "Key" "APP_SENTRY_RELEASE" "Value" .release ) }}
  {{- include "app.configValue" ( dict "Key" "APP_SENTRY_ENVIRONMENT" "Value" ( default $.Release.Name .environment ) ) }}
  {{- include "app.configValue" ( dict "Key" "APP_SENTRY_TRACING" "Value" .tracing ) }}
  {{- include "app.configValue" ( dict "Key" "APP_SENTRY_TRACES_SAMPLE_RATE" "Value" .tracesSampleRate ) }}
  {{- end }}

  # limiter settings
  {{- with .Values.app.limiter }}
  {{- include "app.configValue" ( dict "Key" "APP_LIMITER_API" "Value" .api ) }}
  {{- end }}

  # prometheus settings
  {{- with .Values.app.prometheus }}
  {{- include "app.configValue" ( dict "Key" "APP_PROMETHEUS_ENABLED" "Value" .enabled ) }}
  {{- include "app.configValue" ( dict "Key" "APP_PROMETHEUS_INTERNAL" "Value" .internal ) }}
  {{- include "app.configValue" ( dict "Key" "APP_PROMETHEUS_INTERNAL_PORT" "Value" .internalPort ) }}
  {{- include "app.configValue" ( dict "Key" "APP_PROMETHEUS_EXTERNAL" "Value" .external ) }}
  {{- include "app.configValue" ( dict "Key" "APP_PROMETHEUS_EXTERNAL_PATH" "Value" .externalPath ) }}
  {{- include "app.configValue" ( dict "Key" "APP_PROMETHEUS_PREFIX" "Value" .prefix ) }}
  {{- end }}

  # html2pdf settings
  APP_HTML2PDF_ENDPOINT: "http://{{ .Release.Name }}-html2pdf:3000/"
