{{- $selectorLabels := include "app.selectorLabels" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker"
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ include "app.deploymentReplicas" .Values.app.workerPodScaler }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- $selectorLabels | nindent 8 }}
        app.kubernetes.io/component: worker
      {{- if .Values.app.pods.workerAnnotations }}
      annotations:
        {{- toYaml .Values.app.pods.workerAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.app.image.pullSecret }}
      imagePullSecrets: {{ .Values.app.image.pullSecret }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      containers:
        - name: server
          image: {{ include "app.image" .Values.app.image }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command: [ "dumb-init", "node", "server.js", "worker" ]
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-app-configmap"
            - secretRef:
                name: "{{ .Release.Name }}-app-secrets"
            {{- with .Values.app.pods.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          startupProbe:
            httpGet:
              port: {{ .Values.app.health.port }}
              path: /.health/ready
              scheme: HTTP
          livenessProbe:
            httpGet:
              port: {{ .Values.app.health.port }}
              path: /.health/live
              scheme: HTTP
          readinessProbe:
            httpGet:
              port: {{ .Values.app.health.port }}
              path: /.health/ready
              scheme: HTTP
          ports:
            - name: health
              containerPort: {{ .Values.app.health.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- $selectorLabels | nindent 14 }}
