{{- $selectorLabels := include "app.selectorLabels" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-worker"
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ include "app.deploymentReplicas" .Values.app.workerPodScaler }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      app.local/role: worker
  template:
    metadata:
      labels:
        {{- $selectorLabels | nindent 8 }}
        app.local/role: worker
      {{- if .Values.app.pods.workerAnnotations }}
      annotations:
        {{- with .Values.app.pods.workerAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.app.imagePullSecrets }}
      imagePullSecrets: {{ .Values.app.imagePullSecrets }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.app.image }}"
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          command: ["dumb-init", "node", "server.js", "worker"]
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-app-configmap"
            - secretRef:
                name: "{{ .Release.Name }}-app-secrets"
