{{- if .Values.app.workerPodScaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-worker"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-worker"
  minReplicas: {{ .Values.app.workerPodScaler.minReplicas }}
  maxReplicas: {{ .Values.app.workerPodScaler.maxReplicas }}
  {{- if .Values.app.workerPodScaler.behavior }}
  behavior: {{ .Values.app.workerPodScaler.behavior}}
  {{- else }}
  behavior:
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 60
          type: Pods
          value: 1
        - periodSeconds: 60
          type: Percent
          value: 10
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - periodSeconds: 60
          type: Percent
          value: 10
  {{- end }}
  {{- if .Values.app.serverPodScaler.metrics }}
  metrics: {{ .Values.app.serverPodScaler.metrics }}
  {{- else }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageValue: 500m
  {{- end }}
{{- end }}
