{{- if .Values.app.serverPodScaler.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-server"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-server"
  minReplicas: {{ .Values.app.serverPodScaler.minReplicas }}
  maxReplicas: {{ .Values.app.serverPodScaler.maxReplicas }}
  metrics: {{ .Values.app.serverPodScaler.metrics }}
{{- end }}
