{{- if .Values.app.serverPodScaler.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-server"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Release.Name }}-server"
  minReplicas: {{ .Values.app.serverPodScaler.minReplicas }}
  maxReplicas: {{ .Values.app.serverPodScaler.maxReplicas }}
  {{- if .Values.app.serverPodScaler.metrics }}
  metrics: {{ .Values.app.serverPodScaler.metrics }}
  {{- else }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageValue: 500m
  {{-end }}
{{- end }}
