{
 "title": "Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(app_http_requests_total, environment) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_milliseconds_count{environment=~\"$environment\"}[$__rate_interval])) by (environment)",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "API Latencies",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_milliseconds_bucket{environment=~\"$environment\",path=\"/graphql\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_milliseconds_sum{environment=~\"$environment\"}[$__rate_interval])) by (environment) / sum(rate(app_http_request_duration_milliseconds_count{environment=~\"$environment\"}[$__rate_interval])) by (environment)",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Incoming requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(round(sum(irate(app_http_requests_total{environment=~\"$environment\"}[5m])) by (environment), 0.01))",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Incoming operations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(irate(app_graphql_request_milliseconds_count{environment=~\"$environment\",typename=~\"Query|Mutation\"}[5m])) by (key) != 0)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Operations latencies",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(app_graphql_request_milliseconds_sum{environment=~\"$environment\",typename=~\"Query|Mutation\"}[$__rate_interval])) by (key) / sum(rate(app_graphql_request_milliseconds_count{environment=~\"$environment\",typename=~\"Query|Mutation\"}[$__rate_interval])) by (key)) > 0",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}